version: "3.8"
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB="test_db"
      - POSTGRES_USER="Richard"
      - POSTGRES_PASSWORD="mdp"
    ports:
      - "5432:5432"
  manager:
    build:
        context: "."
        dockerfile: "Dockerfile"
  